### ISSUE TITLE
添加接口文档的建议

### ISSUE THREAD

**Issue by shanaiardor** [pianzide1117/Newbe.CQP.Framework#1]
****

**Comment by shanaiardor** [comment]
仅仅是 注释什么的 根本不够啊

**Comment by pianzide1117** [comment]
将会使用docfx生成api document

**Comment by pianzide1117** [comment]
在线版：
http://yks.oschina.io/newbe.cqp.framework/apidoc/api/index.html
离线版：
http://yks.oschina.io/newbe.cqp.framework/clickonce/setup.exe
